#!/usr/bin/env perl
use warnings;
use strict;
#
# Given an MPG4 Part 14 container stream, dump it
#

use File::Spec;

# allow the libs to be in the bin dir
use FindBin;
use lib File::Spec->catdir($FindBin::RealBin,"lib");
use lib File::Spec->catdir($ENV{HOME},"s/bin/lib");

use MPEG::MP4;

use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Quotekeys = 0;

sub packet_cb {
    my $packet = shift;

    # FIXME - need an option processor
    my $output_bin = 0;

    if ($output_bin) {
        # FIXME - digging around in packets
        my $data = $packet->{_pes_data};

        if (defined($data)) {
            printf("%s",$data);
        }
    } else {
        printf("%s\n",$packet->to_string());
    }

    # FIXME - digging around in object privates
    if (defined($packet->{_data})) {
        $packet->{_data} = substr($packet->{_data},0,16);
    }
    if (defined($packet->{_data_extra})) {
        $packet->{_data_extra} = substr($packet->{_data_extra},0,16);
    }
}

sub main {
    my $ps = MPEG::MP4->new();
    $ps->open($ARGV[0]);

    # TODO - resync when we work out how

    $ps->packet_cb(\&packet_cb);
    while ($ps->read_packets()) { }

    print Dumper($ps);
}
unless (caller) {
    main();
}
